version: '3.1'

services:
  bonjourtravail-api:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    volumes:
      - ./bonjourtravail-api/bin/Debug/net6.0/publish:/app
    ports:
      - 80:80

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/