version: '3.1'

services:
  bonjourtravail-api:
    build: .
    ports:
      - 80:80
    environment:
      PoleEmploi__userId: ${POLE_EMPLOI_USER_ID}
      PoleEmploi__userSecret: ${POLE_EMPLOI_USER_SECRET}
      MongoDatabase__ConnectionString: mongodb://root:example@mongo:27017

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/